In [31]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0]) 

In [33]:
one_hot("amazing restaurant",50)

[3, 23]

In [36]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[22, 26], [3, 23], [23, 18], [48, 13, 24], [40, 17, 23], [13, 26], [26, 17, 31], [1, 13], [1, 20], [21, 46]]


In [37]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
(padded_reviews) 

array([[22, 26,  0],
       [ 3, 23,  0],
       [23, 18,  0],
       [48, 13, 24],
       [40, 17, 23],
       [13, 26,  0],
       [26, 17, 31],
       [ 1, 13,  0],
       [ 1, 20,  0],
       [21, 46,  0]])

In [38]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid')) 

In [39]:
X = padded_reviews
y = sentiment

In [40]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary()) 

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              200       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________
None


In [41]:
model.fit(X, y, epochs=50, verbose=0) 

In [42]:
loss, accuracy = model.evaluate(X, y)
accuracy 

1/1 [==============================] - 0s 188ms/step - loss: 0.6150 - accuracy: 0.9000


0.8999999761581421

In [43]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights) 

50

In [45]:
weights[3] 

array([-0.04577436, -0.09841748,  0.02979449, -0.09561954], dtype=float32)

In [46]:
weights[23]

array([-0.01835302, -0.0773361 ,  0.08807321, -0.05941318], dtype=float32)